### ISSUE TITLE
module 'cv2.aruco' has no attribute 'CharucoBoard_create'

### ISSUE THREAD

**Issue by ansencheung** [lambdaloop/anipose#110]
These are my calibration settings: 
<img width="408" alt="Screenshot 2023-07-25 at 2 33 53 PM" src="https://github.com/lambdaloop/anipose/assets/93555070/736ec4c4-4928-43c2-acc4-7d943d0febc4">
when I run the command anipose draw-calibration, I run into this error: 
<img width="943" alt="Screenshot 2023-07-25 at 2 34 42 PM" src="https://github.com/lambdaloop/anipose/assets/93555070/cc4a8de2-4d6e-4bfa-9827-c8646dfdadd6">

My opencv version is 4.7.0.72. Let me know if more information is needed to solve this issue.

**Comment by philipqueen** [comment]
It appears that the `cv2.aruco` methods were changed in opencv version 4.7: https://stackoverflow.com/questions/75085270/cv2-aruco-charucoboard-create-not-found-in-opencv-4-7-0

You should be able to install an earlier version of opencv with `pip install opencv-contrib-python==4.6.0.66`. It looks like Anipose doesn't specify a version, and should either pin to the last version of opencv that worked with the existing code, or update the aruco methods.

**Comment by ansencheung** [comment]
Ok, I will try to see if that works.

**Comment by dleventh** [comment]
same problem - another quick workaround is to modify the code in the boards module to test the opencv version:

        if cv2.__version__ >= '4.7.0':
            self.board = aruco.CharucoBoard((squaresX, squaresY),
                                             square_length, marker_length,
                                             self.dictionary)
        else:
            self.board = aruco.CharucoBoard_create(squaresX, squaresY,
                                                   square_length, marker_length,
                                                   self.dictionary)

**Comment by abigrassler** [comment]
It looks like @philipqueen has a PR for this up on aniposelib. Can we merge this in @lambdaloop?

**Comment by dleventh** [comment]
Of course.

I've been working on an adaptation of anipose for mirror views that seems to be working reasonably well, but still debugging. It's a little trickier than just applying anipose to reversed mirror images because they need to be undistorted before calibrating.

**Comment by philipqueen** [comment]
> It looks like @philipqueen has a PR for this up on aniposelib. Can we merge this in @lambdaloop?

This PR was merged, so this issue should be able to be marked as closed :)

**Comment by lambdaloop** [comment]
Yes good point!

This is resolved by https://github.com/lambdaloop/aniposelib/pull/21
