### ISSUE TITLE
Reverse triangulation

### ISSUE THREAD

**Issue by hugodwboss** [lambdaloop/anipose#113]
Hi there, 

I am doing multiple data manipulations post triangulation and I was wondering if there is a way to then take the new 3d poses that I created and untriangulate them in 2d poses for each camera views so that I can then label the videos and visualize it in 2d. 

Thanks in advance!

**Comment by RiSpa5** [comment]
Hi, I recently found out that anipose has built-in functions exactly for that porpruse. You can first use `anipose project-2d` which allow 3D data to be reprojected back to 2D. Then you can use `anipose label-2d-proj`, which labels videos using the 2D reprojected data. 
Hope it helps :)

**Comment by hugodwboss** [comment]
Sweet! I will definitely give that a try! Thanks!

**Comment by lambdaloop** [comment]
Yeah that's right! The documentation really needs an uplift based on what we built over the last 2 years.
There's also the anipose visualizer, which makes a web visualizer of your data.

If anyone else happens here for searching, you can also project 3D points to 2D using the CameraGroup.project function [within aniposelib](https://anipose.readthedocs.io/en/latest/aniposelib-api.html#aniposelib.cameras.CameraGroup.project)
