### ISSUE TITLE
How to Utilize GPU for Anipose

### ISSUE THREAD

**Issue by ebtanana** [lambdaloop/anipose#124]
Hello,

I'm still learning the ropes when it comes to Anipose so I was wondering how you can set up Anipose to use my PC's GPU? I just realized I've using my CPU and each video being analyzed runs to around 13 hours per camera. I'm not quite sure how to set my GPU up to work with Anipose. Or perhaps, I'm missing something fundamental

**Comment by LWitter** [comment]
In my experience, if you get DLC to use the GPU, then (in that same environment) Anipose should use the GPU as well since 'anipose analyse' basically just runs DLC.
