### ISSUE TITLE
TypeError during anipose 2d-filter

### ISSUE THREAD

**Issue by SRCM-lab** [lambdaloop/anipose#141]
Hi 

When I run anipose 2d-filter I get the following error: 
`TypeError: cannot properly create the storer for: [_TABLE_MAP] [group->/df_with_missing (Group) '',value-><class 'NoneType'>,format->None`

There is a closed issue with the same problem, but the solution suggested does not work for me. #111 
I commented on the issue 2 weeks ago, but realized it might be better to create a fresh issue, since the issue still persists despite anipose having been updated since, and I have not been able to pull directly from the repository as it was suggested. 
 
The analysis-step creates h5 files as expected, and I am able to run "anipose label-2d" and "anipose calibrate" without an issue, but encounter the same TypeError during "anipose triangulate"

I have attempted the "anipose 2d-filter" command with all available versions of anipose (from 0.8.1 to 1.1.4) with the same result. I have tried both with the tutorial data, and our own data.

I appreciate any suggestions for how I can solve this.

Attached console error, conda list, and config file:
[anipose_clone.Conda.list.txt](https://github.com/user-attachments/files/16428002/anipose_clone.Conda.list.txt)
[Test5_config.txt](https://github.com/user-attachments/files/16428003/Test5_config.txt)
[anipose_clone._Label-2d-filter.txt](https://github.com/user-attachments/files/16428004/anipose_clone._Label-2d-filter.txt)

Best regards, 
Sol

**Comment by lambdaloop** [comment]
Hi @SRCM-lab ,

Could you try updating to anipose to 1.1.8 to see if it fixes the issue?

If not, could you share a sample file from each of pose-2d and pose-2d-filter to help me debug your issue?

Thank you,
Lili

**Comment by SRCM-lab** [comment]
Hi Lili

Thank you for the fast response

The issue seems to have been fixed in 1.1.8

Thank you so much!

Best regards, 
Sol
