### ISSUE TITLE
Converting calibration from Simi

### ISSUE THREAD

**Issue by lambdaloop** [lambdaloop/anipose#18]
How to convert Simi calibration to Anipose or anipose-lib?

This is a continuation of the issue initially posted by @SjoerdBruijn at https://github.com/lambdaloop/anipose/issues/15#issuecomment-599592351

**Comment by SjoerdBruijn** [comment]
Hi there. We have made some progress; managed to set up DLC and anipose for our data, and managed to write a script (matlab, but could easiliy do Python as well) that takes the SIMI calibration files, and returns the calibration.toml. However, so far, the triangulation results don't look appropriate. One thing we were wondering about is the cam_align option; what does this do?

**Comment by lambdaloop** [comment]
@SjoerdBruijn were you able to solve this? Is this still something you're interested in?
I'll close it for now, but feel free to reopen if you're still interested in this.

The `cam_align` option doesn't do anything right now. Eventually, I'd like it to align the calibration relative to a specific camera though.

**Comment by SjoerdBruijn** [comment]
Yes, we've got this to work, apart from the distortion parameters, which SIMI saves in some weird uncompatible format. However, it seems useable. Will provide code soon, however, just back from holiday... (and code needs cleaning..)
