### ISSUE TITLE
Issue installing anipose

### ISSUE THREAD

**Issue by Mirandeitor** [lambdaloop/anipose#2]
Windows 10
Using Anaconda

When I open a terminal in Anaconda to install anipose through pip install i get the following error

 ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Milestone\Anaconda3\envs\anipose\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\MILEST~1\\AppData\\Local\\Temp\\pip-install-xhsfiply\\tables\\setup.py'"'"'; __file__='"'"'C:\\Users\\MILEST~1\\AppData\\Local\\Temp\\pip-install-xhsfiply\\tables\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\MILEST~1\AppData\Local\Temp\pip-install-xhsfiply\tables\
    Complete output (11 lines):
    * Using Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
    * USE_PKGCONFIG: False
    * Found HDF5 using system PATH ('C:\Users\Milestone\Anaconda3\Library\bin')
    * Found conda env: ``C:\Users\Milestone\Anaconda3\envs\anipose``
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\MILEST~1\AppData\Local\Temp\pip-install-xhsfiply\tables\setup.py", line 597, in <module>
        hdf5_version = get_hdf5_version(hdf5_header)
      File "C:\Users\MILEST~1\AppData\Local\Temp\pip-install-xhsfiply\tables\setup.py", line 350, in get_hdf5_version
        major_version = int(re.split("\s*", line)[2])
    ValueError: invalid literal for int() with base 10: 'd'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I have tried to update pip but didn't work. Any idea what is happening?

**Comment by lambdaloop** [comment]
Hello @Mirandeitor,
there seems to be an issue with install pytables. 
What happens when you run `pip install pytables==3.4.4` ? 

Have you tried installing DeepLabCut in a conda environment? You can do so with these instructions:
https://github.com/AlexEMG/DeepLabCut/blob/master/docs/installation.md

If the installing DeepLabCut works, you should be able to install anipose from the same environment.

**Comment by lambdaloop** [comment]
Any updates on trying to install it?

**Comment by lambdaloop** [comment]
Hi @Mirandeitor ,

Do you have any updates on trying to install it?

**Comment by lambdaloop** [comment]
I am not sure if this is still relevant. I will close it for now. 
@Mirandeitor , please reopen if you are still experiencing this.
