### ISSUE TITLE
Triangulation

### ISSUE THREAD

**Issue by niccle27** [lambdaloop/anipose#21]
Hello, 
A few weeks ago, i was asking about the triangulation method you were using. To which you answered using RANSAC and least-means-square method (i suppose it's getting the point minimising the reprojections?).

I tried to look again into your code and the function called when the ransac flag is set (triangulate_ransac) does seem to only reformat the entry. Also in your function (triangulate_simple) you are using the svd method to solve the triangulation, though my mathematical background isn't advanced enough to  be sure of what is beeing done exactly. Is that triangulating optimaly given all the cameras intrinsic and extrinsic matrix and the 2d points for each one?

Could you give me some explaination of the strategy beeing used there ?

I did try to use your pipeline in order to triangulate from multiple cameras. I annotated 51 frames on 5 cameras using deeplabcut. The triangulation from 5 of the cameras with reprojection onto the others helped me annotating 51 frames for a total 11 cameras. (which have been calibrated with the charuco method which led to weird intrinsec parameters, though they were the best qualitative reprojection i could see while proceding on a few reprojections of the pattern using opencv triangulation (by pair)). The reprojection was quite impressive and most of the time, only a few modifications were required.

After proceding to the few corrections of the annotations, i wanted to proceed on triangulating then reprojecting every view together in order to train a robust network using deeplabcut.

Unfortunnately, results are quite random and i have absolutely no idea how to fix it.
https://www.pixenli.com/image/lzSAoGAq

I'll let you the anipose pipeline i used to triangulate and the results i got.
https://we.tl/t-MsJF3ki9sG
 
Though the triangulation with five cameras (1,2,7,9,12) was working pretty well and was computed in less than 4 seconds, the calibration with 11 cameras took arround 4 minutes on the same computer.

PS: the camera 5 has been erased as the camera was never able to see the hand on the videos i have, the configuration file has been adapted consequently.

Thank you a lot for you work once again !

**EDIT**
I continued my research in order to isolate the problem. There seem to be an issue when using up to 10 cameras, it seems to work fine : 
Exemple using : cam [1,2,3,4,6,7,8,9,10,12] and [1,2,3,4,6,7,8,9,11,12] 

Though as soon as i'm using 11 cameras together, the results became messy and is not usable at all

**Comment by lambdaloop** [comment]
Hi @niccle27 ,

I apologize for getting back so late.

Yes, the SVD method is a standard technique for triangulation with multiple cameras. 
It can fail with incorrect keypoint detections though, hence why RANSAC and optimizing the reprojection loss with a robust loss function can be useful. 

Still, I'm intrigued by your problem. I must admit that I've only tried Anipose with up to 6 cameras, so I'm not sure exactly what is happening in the realm of 11+ cameras. 

Could you send me some example tracking and calibration videos? I noticed you uploaded the folders, but it seems that they got deleted. If you'd like you can also email them to me privately at krchtchk@gmail.com , if that is more comfortable.

**Comment by niccle27** [comment]
Hi @lambdaloop ,

Yes i fully agree that the RANSAC and reprojection optimization is a good idea, but i wasn't able to locate the part of your code where you actually make those... Would it be possible to orientate me to the specific location in your project ? 

I'm gonna try to send a project for you to reproduce it today. Indeed, the issue was quite weird... Maybe the SVD system is to constrainted to be able to converge.

**Comment by lambdaloop** [comment]
Hi @niccle27 ,

Sure, the core `anipose triangulate` starts here: https://github.com/lambdaloop/anipose/blob/master/anipose/triangulate.py#L166

It calls the functions from triangulate, triangulate_ransac, or triangulate_optim from aniposelib depending on the parameters. The implementation in aniposelib is here:

**Comment by niccle27** [comment]
Hi @lambdaloop 
I already tried to explore the different functions and i already gent into the triangulation function you just showed. Indeed you have a ransac flag that lead the triangulation process to use this function: 
https://github.com/lambdaloop/aniposelib/blob/df1fa98d6c6c5b17a8823ca172d8d45015336044/aniposelib/cameras.py#L596

Though as far as i can see, that function is just formatting the data and not currently proceeding in an outliers detection. Therefore could you lead me to the portion of your code where the ransac is implemented ? I was also wondering whether you were proceding in a bundle adjustment for triangulation as well ? Or is that just part of the calibration procedure?

Thank you a lot for your time !

**Comment by lambdaloop** [comment]
Hi @niccle27 ,
The triangulate_ransac function calls the triangulate_possible function, which implements a more general version of RANSAC (which supports any number of points per camera). Does that make sense?

The triangulation method which implements an optimization procedure similar to bundle adjustment is `triangulate_optim`, which starts here: https://github.com/lambdaloop/aniposelib/blob/df1fa98d6c6c5b17a8823ca172d8d45015336044/aniposelib/cameras.py#L1159

Hopefully that makes sense, let me know if you have more questions!
