### ISSUE TITLE
calibration-errors results in "Import error cannot import name 'get_board_type'"

### ISSUE THREAD

**Issue by PolarBean** [lambdaloop/anipose#25]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lambdaloop** [comment]
seems like a duplicate with https://github.com/lambdaloop/anipose/issues/26 , closing
