### ISSUE TITLE
Question: GPU Usage

### ISSUE THREAD

**Issue by omeleavitt** [lambdaloop/anipose#27]
I'm currently running through the tutorial in a "clean" environment on a computer that successfully runs DeepLabCut (in a different environment) with the GPU. Does the Anipose environment use the GPU by default or does the installation require the DLC GPU installation with Anipose on top?

**Comment by lambdaloop** [comment]
Seems like you've resolved this.

For anyone else that lands on this question, Anipose just uses the installed DeepLabCut as is. It will use the GPU if and only if DeepLabCut uses the GPU.
