### ISSUE TITLE
label-3d Version Conflict

### ISSUE THREAD

**Issue by Guillermo-Hidalgo-Gadea** [lambdaloop/anipose#33]
Hi guys,
After anipose analyze, filter, calibrate and triangulate I wanted to label 2d and 3d videos. 2d videos worked fine, but label-3d seemed to have a pkg_resource.ContextualVersionConflict with pyface. 
Downgrading from pyface==7.0.1 to pyface==6.1.2 solved the problem, and 3d video looks great. 
Thank you for these awesome tools.

**Comment by lambdaloop** [comment]
Huh interesting.. Thank you for letting us know!
We don't currently fix the version of pyface. I'm not sure what issues would arise if we fix it to 6.1.2? 
I guess I'll mark this as resolved for now and maybe add a note in the documentation about this. 

Thank you for the kind words!
