### ISSUE TITLE
How can i fix the error about OpenGL.

### ISSUE THREAD

**Issue by Jungjihyuk** [lambdaloop/anipose#35]
When i run command 'anipose label-3d', i encountered an error that cannot create GLX context.
![error](https://user-images.githubusercontent.com/33630505/88654033-c519cc80-d107-11ea-978c-0b53b0b237e4.png)

My development environment is as follow.
OS: Ubuntu 16.04 
GPU: RTX 2080 Ti 
I'm using 'ssh -Y remoteserver' in terminal 
 
please let me know if you need more information about my environment.

**Comment by lambdaloop** [comment]
Hi @Jungjihyuk 
Yes, this can happen on linux if you run it without an appropriate display. 
If you already have a GUI (X session) running and you're logging in remotely, you can set the DISPLAY variable to match the GUI, like so:
```export DISPLAY=:0```
The number 0 may need to be 1 or 2, depending on what number the display ended up being.

If you don't have a GUI running, you can make a fake one by using `Xvfb` in a separate console:
```Xvfb :9 -screen 0 1280x1024x24 -auth localhost```
This essentially creates a fake screen with display :9. If you do this, you can then set `export DISPLAY=:9` before running `anipose label-3d`

**Comment by Jungjihyuk** [comment]
Oh!! You were a big help to me. 
I really appreciate your feedback!!
