### ISSUE TITLE
How to set reference plane in 3d video

### ISSUE THREAD

**Issue by Guillermo-Hidalgo-Gadea** [lambdaloop/anipose#36]
I am running a project with several sessions to triangulate human faces, and the final 3d videos (and combined videos) are upside down, and also inconsistently rotated between session, although 2d videos have all the same orientation. 
Is there any setting in label_videos_3d.py or label_combined.py to set specific markers or even a specific plane in the 3D space to rotate the final 3d videos to a common orientation?

**Comment by lambdaloop** [comment]
Hello @Guillermo-Hidalgo-Gadea ,

Yes, we support having a standard 3D pose! 

The documentation for it is here:
https://anipose.readthedocs.io/en/latest/start3d.html#configuring-the-standardized-3d-pose

However, looking at it again, seems like the code example didn't render properly. We'll have to look into it. 
In the meantime, you can read the same example here:
https://github.com/lambdaloop/anipose/blob/master/docs/github/start_3d.md#configuring-the-standardized-3d-pose

**Comment by Guillermo-Hidalgo-Gadea** [comment]
Hello @lambdaloop, 
I just tried the settings you mentioned above and repeated triangulation and label-3d. 
Everything worked fine and the objects can be rotated to the convenient orientation smoothly.
Thank you
