### ISSUE TITLE
Good detections but bad calibration

### ISSUE THREAD

**Issue by johnmbarrett** [lambdaloop/anipose#41]
Apologies if this has been addressed before, I had a look through the existing issues and nothing quite match.

Basically, the first few times I used anipose it worked great. Since then, however, more often than not I get bizarre results out of the calibration. Manually verifying the marker detections, they're usually >99% correct. The reprojection error is low, often <1. But when I check the calibration parameters, they don't make sense, e.g. the "cameras"* are both within a couple millimeters of the world origin and pointing in virtually the same direction. This in turn leads to implausible triangulation, i.e. the mouse that I'm tracking is either microscopic or several meters tall.

Am I doing something wrong? Or have I run into a pathological case for anipose's camera calibration algorithm? Calibration videos are [here](https://drive.google.com/file/d/1lzmnYf5YlP-TXUz0CdZn3_1pc51UFAzs/view?usp=sharing) and [here](https://drive.google.com/file/d/1-i_clNb6nnC8O_5hW8enWTDnOenaVSrs/view?usp=sharing). Attached are [the project config](https://github.com/lambdaloop/anipose/files/5235806/config.toml.txt), [the calibration target](https://user-images.githubusercontent.com/19190699/93411480-e160fc80-f860-11ea-93cb-2f726c549ca9.png), [the detections file](https://github.com/lambdaloop/anipose/files/5235813/detections.pickle.txt), [the resultant calibration file](https://github.com/lambdaloop/anipose/files/5235816/calibration.toml.txt). I've tried things like turning fisheye on or off, turning ransac on and off, and changing the camera used for alignment, and get basically the same results each time.

*I'm actually using a single camera with a prism and a pair of mirrors to get two views of the subject. Could it be that anipose's camera calibration just doesn't work in this case? It does get it right (or at least comes up with a plausible solution) sometimes though.

Thanks in advance for your help and thanks for anipose in general, when I can get it to work it's great! Please let me know if you need any more info.

**Comment by ljahn** [comment]
I also encountered this once. Funny enough, the triangulated 3D coordinates were perfectly fine in my case. I noticed that this behavior becomes less likely when using more calibration images. I now always use at least 80 pictures per camera and it never happened again so far.

**Comment by johnmbarrett** [comment]
Number of images isn't the issue in my case. I can have 100s of images per camera, all with perfect detections (I've checked), and still get wacky results.

**Comment by lambdaloop** [comment]
Hmm, I'm not sure if the Anipose camera model is generic enough for working with a single camera split by a prism. 
The camera model is highly constrained right now, to give a better chance at getting a good calibration, but it does mean that it'll fail in cases like this.

Do you flip the image that you get from the prism before passing it through the calibration?

**Comment by johnmbarrett** [comment]
There are an even number of reflections along both optical paths, so they cancel out, hence no need to flip (just to be safe I checked: things that appear on the left in one view are on the left in the other, etc.). How easy is it for users to swap out the camera model used by anipose? If I get a chance I'll work out what transformations the prism is introducing and from there what needs to be added to the model. Off the top of my head the prism will be introducing its own magnification (in addition to that of the camera lens), not sure what else.

In any case, I've found a sort of workaround. I remembered reading about the undocumented `calibration_init` referenced in https://github.com/lambdaloop/anipose/issues/1. My setup doesn't move around too much between experiments, so I set `calibration_init` to the calibration file from one of the times anipose was able to find a sensible solution, and for now I seem to get sensible results for all my experiments.

**Comment by lambdaloop** [comment]
Anipose uses the camera model described here:
https://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html

However, it fixes f_x = f_y, sets c_x and c_y to be the center of the image, and assumes only the first distortion coefficient is nonzero. I suspect that for a prism, each of these assumptions may need to be relaxed. 
If you wanna play around with it, the parameters are restricted at this line in aniposelib: https://github.com/lambdaloop/aniposelib/blob/master/aniposelib/cameras.py#L279
At some point, I would like to make this more configurable, but I'm not sure when I'll get around to it.

**Comment by ConnorM17** [comment]
@johnmbarrett I am having a similar issue to yours. In my case I am using 4 cameras in an arc like formation. Every time I run my calibration I get wacky results too. Even calibrating with 7000+ images the camera focal lengths vary drastically and the rotation and translation vectors seem to make no sense. Did you find a solution other than initializing a previous calibration?

@lambdaloop Have you ever had this issue? In my 4 camera setup the cameras are around 1.0m to 2.0m apart. however the translations that are obtained indicate that the calibration origin (arbitrary points selected during calibration I guess?) is only a few millimeters away from each camera...which doesn't seem to make any physical sense.

**Comment by saulzar** [comment]
Having played around with it a little for calibrating a 6 camera rig - I enabled more fancy distortion coefficients which seemed to help in some cases... but the main issue seems to be estimating the focal length. 

In one set of images (using the same calibration pattern) it is roughly correct (4800 vs 4400), but in another it is way off (50 vs 4400) - any idea what can cause that? Outliers?

**Comment by saulzar** [comment]
Calibrating each camera first with OpenCV (cv2.calibrateCamera) seems to make a huge difference, so it seems in my case the initialisation of the intrinsics might be not good?

**Comment by ConnorM17** [comment]
I have switched to my own code based on OpenCV's calibration tools (cv2.calibrateCamera/stereoCalibrate/etc.). I seem to get much repeatable results and they make more physical sense as well. Not sure why results from Anipose calibration seem to have high variance...I use the same calibration data on my own code and Anipose's and get different results, sometimes they are roughly correct as you found

**Comment by lambdaloop** [comment]
@johnmbarrett I've run this again with the latest aniposelib (version 0.4.3) , which fixes [an issue](https://github.com/lambdaloop/anipose/issues/48) with the camera intrinsics initialization and it seems to work better, at least for the example detections you provided. 

For instance, I get this calibration now for the detection files you provided:
[calibration.toml.txt](https://github.com/lambdaloop/anipose/files/7271851/calibration.toml.txt)

I have run it 3 times now and it seems to give me much more consistent results too. 

So for anyone observing this, I now recommend upgrading to the latest aniposelib (>= 0.4.3) and seeing if the issue persists.

**Comment by lambdaloop** [comment]
This is an old issue and I think it is fixed now, but if you have other files that you've tried since upgrading and they *still* don't work then please feel free to reopen or file a new issue.
