### ISSUE TITLE
[DOC] Installation opencv-python and opencv-contrib-python

### ISSUE THREAD

**Issue by alexrockhill** [lambdaloop/anipose#44]
When installing on Ubuntu 18.04, if opencv-python is already installed then when opencv-contrib-python is installed, aruco and the rest of the development open-cv modules are not installed due to the package conflict. This could be documented in the installation possibly.

**Comment by lambdaloop** [comment]
Ah, this issue has been plaguing me for some time.. 
Looking back at `opencv-contrib-python` docs, they actually do recommend removing `opencv-python` for proper installation, so I've made a note of that now in the docs. 

Thank you for heads up!
