### ISSUE TITLE
[BUG] Calibration Squares not the same size as demo

### ISSUE THREAD

**Issue by alexrockhill** [lambdaloop/anipose#45]
When I print out the calibration.png from here https://drive.google.com/drive/u/1/folders/18qGbHyiSJ2au9sFXScZ63EZ83PtC1-ld, it measures 28 mm instead of 25 mm in as in the toml config file. This is likely because it doesn't have the margins that are shown in the calibration clipboard videos.

**Comment by alexrockhill** [comment]
A pdf that looks correct can be downloaded from here https://calib.io/pages/camera-calibration-pattern-generator and that I measured to be correct and matches what is in the calibration video. Maybe it's better to suggest in the documentation to buy an official calibration board but there is a pdf download too.

**Comment by alexrockhill** [comment]
![calibration_letter](https://user-images.githubusercontent.com/13473576/93539503-d7dda000-f905-11ea-828b-cf78d2ab1102.png)

I made this calibration by taking an 11 x 8.5 inch canvas and pasting the image scaled to 250 x 170 mm. I haven't printed and measured to confirm yet but I think this would be better.

**Comment by alexrockhill** [comment]
Would it be worth a PR to make an image with the correct margins to be printed on a letter size paper? I guess it would probably need to go in the google drive though...

**Comment by lambdaloop** [comment]
I'd accept the PR that does that (it would probably go into [aniposelib](https://github.com/lambdaloop/aniposelib/)) , but I'm not sure if it's worth writing up the code. As you mentioned, the calib.io pattern generator already works quite well and is really customizable. 

I can add a calibration pdf image in the google drive though.
