### ISSUE TITLE
Calibration - anipose not detecting checkerboard pattern #SOLVED

### ISSUE THREAD

**Issue by Coco1234Coco** [lambdaloop/anipose#46]
Hi,

whenever I run anipose calibrate I end up with 0 detected checkerboard patterns. I tried different calibration videos and different config.toml settings.

I use a 11x8 checkerboard with a square side length of 25mm. So far I did the following:
set `board_size` to `[11,8]` or `[275, 200]`. I used the latter cause of the documentation saying the units should be consistent. 
Anyway, using [11,8] or [275,200] with `board_square_side_length = 25` always leads to zero detected checkerboards.
I also tried all above combinations with `board_marker_length = 25`, though I think that this code is not necessary when using checkerboards.

My folder structure is as followed:
```
rect_check--2020-09-16    (DLC model folder)
rect_check          (anipose project folder)
|  config.toml
|  calibration
|     --- calib_left.avi
|     --- calib_right.avi
|  pose-2d
|  videos_raw
|     --- 011_left.avi
|     --- 011_right.avi
|     --- 012_left.avi
|     --- 012_right.avi ...
```
and I use `nesting = 1`.
I attached the config.toml.

[config.zip](https://github.com/lambdaloop/anipose/files/5260417/config.zip)

**Comment by ljahn** [comment]
I think it could be that you are counting the squares but anipose is counting the lattice crossings.
Try `board_size = [10, 7]` and `board_square_side_length = 0.025 # m`.

**Comment by lambdaloop** [comment]
I don't have much to add on Ijahn's suggestion (thank you @ljahn !). 

The calibration parameters are documented here:
https://anipose.readthedocs.io/en/latest/params.html#parameters-for-calibration
I noticed that the `board_size` description was incorrect, which is where the confusion may be coming from. 
I fixed it to say the following:
```board_size: Width and height of grid. Should be the number of inner corners per side for checkerboard, or squares for charuco.```

The square side length can really be of any size, it'll just specify the units that you're working in. 
Setting it to be 25 when your board is 25 mm per square means that you'll be working in mm.

**Comment by Coco1234Coco** [comment]
Hey,

thank you both for your quick replies! I‘m currently on vacation but will try the recommended settings as soon as I‘m back!
I‘ll also let you know if these settings work or not. 

So long,
Conrad

**Comment by Coco1234Coco** [comment]
Hey @Ijahn, hey @lambdaloop,

changing the checkerboard size to the numbers of inner corners did the deal. There are now as many checkerboards detected as there are video frames in the calibration videos.
Unfortunately I ran straight into another issue. This is what my console output looks like.

> cd C:\Conrad\AniPose\rect_check

> (anipose_conrad) C:\Conrad\AniPose\rect_check>anipose calibrate
> Calibrating...
> C:\Conrad\AniPose\rect_check\videos_raw
> C:\Conrad\AniPose\rect_check\calibration\calibration.toml
> C:\Conrad\AniPose\rect_check\calibration\camA.avi
> 100%|███████████████████████████████| 496/496 [00:07<00:00, 66.20it/s]
> 496 boards detected
> C:\Conrad\AniPose\rect_check\calibration\camB.avi
> 100%|███████████████████████████████| 496/496 [00:07<00:00, 67.90it/s]
> 496 boards detected
> defaultdict(<class 'int'>, {})
> Traceback (most recent call last):
>   File "c:\users\bknuser\anaconda3\envs\anipose_conrad\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\users\bknuser\anaconda3\envs\anipose_conrad\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\bknUser\anaconda3\envs\anipose_conrad\Scripts\anipose.exe\__main__.py", line 7, in <module>
>   File "c:\users\bknuser\anaconda3\envs\anipose_conrad\lib\site-packages\click\core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "c:\users\bknuser\anaconda3\envs\anipose_conrad\lib\site-packages\click\core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "c:\users\bknuser\anaconda3\envs\anipose_conrad\lib\site-packages\click\core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "c:\users\bknuser\anaconda3\envs\anipose_conrad\lib\site-packages\click\core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "c:\users\bknuser\anaconda3\envs\anipose_conrad\lib\site-packages\click\core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "c:\users\bknuser\anaconda3\envs\anipose_conrad\lib\site-packages\click\decorators.py", line 73, in new_func
>     return ctx.invoke(f, obj, *args, **kwargs)
>   File "c:\users\bknuser\anaconda3\envs\anipose_conrad\lib\site-packages\click\core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "c:\users\bknuser\anaconda3\envs\anipose_conrad\lib\site-packages\anipose\anipose.py", line 116, in calibrate
>     calibrate_all(config)
>   File "c:\users\bknuser\anaconda3\envs\anipose_conrad\lib\site-packages\anipose\common.py", line 168, in fun
>     return process_all(config, process_session, **args)
>   File "c:\users\bknuser\anaconda3\envs\anipose_conrad\lib\site-packages\anipose\common.py", line 153, in process_all
>     output[past_folders] = process_session(config, path, **args)
>   File "c:\users\bknuser\anaconda3\envs\anipose_conrad\lib\site-packages\anipose\calibrate.py", line 203, in process_session
>     verbose=True)
>   File "c:\users\bknuser\anaconda3\envs\anipose_conrad\lib\site-packages\aniposelib\cameras.py", line 1563, in calibrate_rows
>     rvecs, tvecs = get_initial_extrinsics(rtvecs)
>   File "c:\users\bknuser\anaconda3\envs\anipose_conrad\lib\site-packages\aniposelib\utils.py", line 174, in get_initial_extrinsics
>     extrinsics = compute_camera_matrices(rtvecs, pairs)
>   File "c:\users\bknuser\anaconda3\envs\anipose_conrad\lib\site-packages\aniposelib\utils.py", line 164, in compute_camera_matrices
>     source = pairs[0][0]
> IndexError: list index out of range

Please note: Since I'm really new to all this and not really acquainted with regex, I changed the video suffixes from _left / _right to -camA and -camB to replicate the naming pattern of the anipose 3d tutorial files. So instead of calibration_left and calibration_right or 011_left, 011_right the videos names are now calib-camA, calib-camB, 011-camA, 011-camB and so on. I did this as some kind of error elimination, assuming errors arise from my limited understanding and so must originate in the config files I wrote oder the nesting I used.

**Comment by Coco1234Coco** [comment]
Hey folks,
unfortunately I encountered another error when using `anipose draw-calibration` (please note: the draw_calibration command as can be found in the tutorial does not work on my machine; I read some stuff about how some are having trouble using draw-calibration while other encounter problems using draw_calibration).

Here's my console output from the `anipose calibrate` command:

> (anipose_conrad) C:\Conrad\AniPose\rect_check>anipose calibrate
> Calibrating...
> C:\Conrad\AniPose\rect_check\videos_raw
> C:\Conrad\AniPose\rect_check\calibration\calibration.toml
> C:\Conrad\AniPose\rect_check\calibration\calib-camA.avi
> 100%|███████████████████████████████| 496/496 [00:07<00:00, 62.58it/s]
> 496 boards detected
> C:\Conrad\AniPose\rect_check\calibration\calib-camB.avi
> 100%|███████████████████████████████| 496/496 [00:07<00:00, 64.22it/s]
> 496 boards detected
> defaultdict(<class 'int'>, {('A', 'B'): 496, ('B', 'A'): 496})
> error:  0.6628271021507182
> n_samples: 100
> {(0, 1): (300, array([0.24596805, 1.22442333]))}
> error: 0.77, mu: 1.2, ratio: 0.750
>    Iteration     Total nfev        Cost      Cost reduction    Step norm     Optimality
>        0              1         6.9172e+01                                    6.77e+04
>        1              2         2.7653e+01      4.15e+01       2.55e+02       8.30e+04
>        2              3         7.9481e+00      1.97e+01       1.40e+01       1.11e+02
>        3              5         7.9295e+00      1.86e-02       2.89e+01       4.79e+02
>        4              6         7.9268e+00      2.67e-03       1.27e+00       4.59e+01
>        5              7         7.9262e+00      6.42e-04       1.77e+01       5.96e+02
> `ftol` termination condition is satisfied.
> Function evaluations 7, initial cost 6.9172e+01, final cost 7.9262e+00, first-order optimality 5.96e+02.
> {(0, 1): (300, array([0.04102891, 0.24840634]))}
>    Iteration     Total nfev        Cost      Cost reduction    Step norm     Optimality
>        0              1         6.7593e+03                                    9.89e+03
>        1              2         2.3841e+03      4.38e+03       7.12e+02       2.42e+04
>        2              3         7.3452e+01      2.31e+03       7.01e+02       5.42e+04
>        3              4         1.6386e+01      5.71e+01       1.19e+02       7.16e+02
>        4              5         1.6147e+01      2.39e-01       6.47e+00       2.62e+01
>        5              6         1.6146e+01      1.34e-03       8.97e+00       4.22e+01
> `ftol` termination condition is satisfied.
> Function evaluations 6, initial cost 6.7593e+03, final cost 1.6146e+01, first-order optimality 4.22e+01.
> {(0, 1): (300, array([0.02411355, 0.19027024]))}
> error:  0.09656505970863771
> error:  0.09525074330664995
> n_samples: 100
> {(0, 1): (1000, array([0.02886056, 0.21711679]))}
>    Iteration     Total nfev        Cost      Cost reduction    Step norm     Optimality
>        0              1         3.2302e+02                                    4.75e+03
>        1              2         5.6714e+01      2.66e+02       1.74e+02       2.12e+04
>        2              3         5.1657e+01      5.06e+00       1.49e+01       3.92e+01
>        3              4         5.1643e+01      1.37e-02       7.35e+00       1.49e+02
>        4              5         5.1641e+01      2.39e-03       3.56e+00       2.51e+02
> `ftol` termination condition is satisfied.
> Function evaluations 5, initial cost 3.2302e+02, final cost 5.1641e+01, first-order optimality 2.51e+02.
> {(0, 1): (1000, array([0.02645003, 0.20000202]))}
> error:  0.09521903355103017
> C:\Conrad\AniPose\rect_check\pose-2d
> C:\Conrad\AniPose\rect_check\calibration\calibration.toml
> C:\Conrad\AniPose\rect_check\calibration
> C:\Conrad\AniPose\rect_check\calibration\calibration.toml

After the calibration procedure I end up with a `calibration.toml` and `calibration.pickle` under "/calibration/". 

I then tried the `anipose draw-calibration` command, that gave me the following error:

> (anipose_conrad) C:\Conrad\AniPose\rect_check>anipose draw-calibration
> Drawing calibration board...
> Traceback (most recent call last):
>   File "c:\users\bknuser\anaconda3\envs\anipose_conrad\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\users\bknuser\anaconda3\envs\anipose_conrad\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\bknUser\anaconda3\envs\anipose_conrad\Scripts\anipose.exe\__main__.py", line 7, in <module>
>   File "c:\users\bknuser\anaconda3\envs\anipose_conrad\lib\site-packages\click\core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "c:\users\bknuser\anaconda3\envs\anipose_conrad\lib\site-packages\click\core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "c:\users\bknuser\anaconda3\envs\anipose_conrad\lib\site-packages\click\core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "c:\users\bknuser\anaconda3\envs\anipose_conrad\lib\site-packages\click\core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "c:\users\bknuser\anaconda3\envs\anipose_conrad\lib\site-packages\click\core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "c:\users\bknuser\anaconda3\envs\anipose_conrad\lib\site-packages\click\decorators.py", line 73, in new_func
>     return ctx.invoke(f, obj, *args, **kwargs)
>   File "c:\users\bknuser\anaconda3\envs\anipose_conrad\lib\site-packages\click\core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "c:\users\bknuser\anaconda3\envs\anipose_conrad\lib\site-packages\anipose\anipose.py", line 287, in draw_calibration
>     cv2.imwrite('calibration.png', img)
> cv2.error: OpenCV(3.4.11) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-lw30ardm\opencv\modules\imgcodecs\src\loadsave.cpp:759: error: (-215:Assertion failed) !_img.empty() in function 'cv::imwrite'

I checked back with the anipose manual. It says: 

> If you have specified your calibration marker in the configuration (as above), you can use anipose to draw it. This can be useful for checking whether the configuration is correct, or for drawing arbitrary calibration boards.

I'm wondering if the draw-calibration or draw_calibration command can only be used with boards that have markers (since the manual says "[...] have specified you calibration marker [...]") or also to draw checkerboard calibration boards / patterns?

I'm really sorry for bothering you with this barrage of questions and error messages that most likely are on my end. But my superior wants to implement deeplabcut or more precise anipose as a cheap, hopefully accurate and most important mobile alternative to expensive and bulky motion tracking systems. I'd be thrilled to come up with some promising results and an intuitive workflow for image acquisition (I did that already, though I'm having some performance issues with 60fps full hd frame acqusition via 2 cameras on the same machine) and triangulation (where I'm stuck now). I tried the 3d capabilities of DeepLabCut but after reading your paper I'm excited to get anipose working since your filtering results in "Anipose: a toolkit for robust markerless 3D pose estimation" seem very promising for our use case.

Cheers,
Conrad
