### ISSUE TITLE
Calibration error

### ISSUE THREAD

**Issue by menor22** [lambdaloop/anipose#5]
Hi,

I encounter a problem when a want to calibrate my cameras.
Videos containing checkerboard are analyzed and boards are detected but then an error occurs (cv2.error).

I tried to downgrade the opencv version to 3.4 as you mentioned in a previous issue but the same error message appears.

C:\Users\ormen\Desktop\anipose\Patient1\Nothing\calibration\Cam1_Calibration_1_10-29-19_11-29-34.avi
100%|█████████████████████████████| 1482/1482 [01:52<00:00, 13.23it/s]
1346 boards detected
C:\Users\ormen\Desktop\anipose\Patient1\Nothing\calibration\Cam2_Calibration_1_10-29-19_11-29-34.avi
100%|█████████████████████████████| 1482/1482 [01:20<00:00, 18.51it/s]
1394 boards detected
Traceback (most recent call last):
  File "c:\users\ormen\anaconda3\envs\dlc-windowsgpu\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ormen\anaconda3\envs\dlc-windowsgpu\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ormen\Anaconda3\envs\dlc-windowsGPU\Scripts\anipose.exe\__main__.py", line 9, in <module>
  File "c:\users\ormen\anaconda3\envs\dlc-windowsgpu\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\ormen\anaconda3\envs\dlc-windowsgpu\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\ormen\anaconda3\envs\dlc-windowsgpu\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\ormen\anaconda3\envs\dlc-windowsgpu\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\ormen\anaconda3\envs\dlc-windowsgpu\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\ormen\anaconda3\envs\dlc-windowsgpu\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "c:\users\ormen\anaconda3\envs\dlc-windowsgpu\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\ormen\anaconda3\envs\dlc-windowsgpu\lib\site-packages\anipose\anipose.py", line 108, in calibrate
    calibrate_all(config)
  File "c:\users\ormen\anaconda3\envs\dlc-windowsgpu\lib\site-packages\anipose\common.py", line 168, in fun
    return process_all(config, process_session, **args)
  File "c:\users\ormen\anaconda3\envs\dlc-windowsgpu\lib\site-packages\anipose\common.py", line 153, in process_all
    output[past_folders] = process_session(config, path, **args)
  File "c:\users\ormen\anaconda3\envs\dlc-windowsgpu\lib\site-packages\anipose\calibrate.py", line 183, in process_session
    n_samp_iter=100, n_samp_full=2000)
  File "c:\users\ormen\anaconda3\envs\dlc-windowsgpu\lib\site-packages\calligator\cameras.py", line 1546, in calibrate_rows
    all_rows[i] = board.estimate_pose_rows(cam, row)
  File "c:\users\ormen\anaconda3\envs\dlc-windowsgpu\lib\site-packages\calligator\boards.py", line 333, in estimate_pose_rows
    row['ids'])
  File "c:\users\ormen\anaconda3\envs\dlc-windowsgpu\lib\site-packages\calligator\boards.py", line 465, in estimate_pose_points
    reprojectionError=30)
cv2.error: OpenCV(3.4.7) C:\projects\opencv-python\opencv\modules\calib3d\src\solvepnp.cpp:216: error: (-215:Assertion failed) npoints >= 4 && npoints == std::max(ipoints.checkVector(2, CV_32F), ipoints.checkVector(2, CV_64F)) in function 'cv::solvePnPRansac'

Do you have an idea what can be the problem? 

Best,

Y

**Comment by lambdaloop** [comment]
Hi @menor22,

That's an interesting error. It seems that I had the wrong threshold for the number of points needed for pose estimation of the checkerboard. It should be 4 instead of 3. I fixed this and updated calligator.

Could you try updating calligator ( `pip install --upgrade calligator` ) and seeing if that fixes it?

If it does not fix it, could you share you calibration files so that I can try to reproduce the error?

Thank you!
Pierre

**Comment by menor22** [comment]
Hi Pierre,

So I tried to upgrade calligator but I got the same error message.

Please find attached my config file (in .txt since I can't join .toml files) and videos for calibration.

Thanks for your help!

Yannick

[Calib_vidz.zip](https://github.com/lambdaloop/anipose/files/3802167/Calib_vidz.zip)



[config.txt](https://github.com/lambdaloop/anipose/files/3802156/config.txt)

**Comment by lambdaloop** [comment]
Hi @menor22 ,

I tried reproducing your issue, but unfortunately, I cannot. I seem to get slightly different detections and then it runs fine... I tried running it with both OpenCV 3.4.7 and OpenCV 3.4.5 .

For reference, here is what I get as output:
https://drive.google.com/open?id=1aNiSSCanT6Aujlm6-Ct9UXO_-xv4iadq

I suspect there must be some kind of invalid detection that throws it off when it tries to estimate the pose. Could you share your `detections.pickle` file? Perhaps I could find which one it is to patch calligator. Feel free to zip if it needed to share it.

Thank you!
Pierre

**Comment by menor22** [comment]
Ok, so it was probably a problem with my video files (too big? >1 Gb). I tried with the one I sent you (compressed) and now it's working fine.

I need a reference frame but I don't really understand the matrix in the config file:

```
﻿[triangulation]
axes = [
    ["x", "L1A", "L3A"],
    ["z", "L1B", "L1A"]
]
reference_point = "L1A"

What should I change for my camera settings?

Best,

Y


```

**Comment by lambdaloop** [comment]
Hi @menor22, 

Glad that it is working well! If you still have the detections.pickle file for the big video files, I would still appreciate seeing it, so that I can fix the bug you encountered.

For the reference frame, the documentation for it is here:
https://github.com/lambdaloop/anipose/blob/master/docs/start_3d.md#configuring-the-standardized-3d-pose

Depending on your setup, you might label additional stationary points to use for a reference frame.

--Pierre

**Comment by menor22** [comment]
Hi Pierre,

Please find attached the detections.pickle file.

So if I understand well I have to label (from deeplabcut) fixed points to use them for reference frame?
I guess that using bodyparts for reference frame is not a good idea (e.g. ['x','shoulderR','wristR'], ...)? 

Best,

Y

[detections.zip](https://github.com/lambdaloop/anipose/files/3803345/detections.zip)

**Comment by lambdaloop** [comment]
Hi @menor22 ,

Thank you for providing the detections! I was able to reproduce your bug. I'm not sure why, but for some reason on some frames there were some checkerboards detected with the invalid number of points. I added a check for that in calligator and it seems to work now.

Could you update calligator and try again?

For reference frames, anipose sets a fixed reference frame per video, using the median values for the point locations. If your points do not move much or move around some location periodically, then it should be fine to use them for reference. If they move around too much, then with the current algorithm the reference frame may not mean much.

Thank you!
Pierre

**Comment by menor22** [comment]
Hi Pierre,

So I updated calligator and it works now, thanks a lot.

For the reference point it's not possible to define a fixed value by providing x and y coordinates (and same for the axis) instead of add a new label in deeplabcut?

Best,

Yannick

Best, 

Yannick

**Comment by lambdaloop** [comment]
Hi Yannick,

Great! I'm glad this fixed it.

Unfortunately, anipose doesn't currently support a reference frame with static x and y coordinates per image. Perhaps you could file an issue for this, I can get around to it eventually. 

Best,
Pierre

**Comment by menor22** [comment]
Hi Pierre,

Sure, I will work on it and let you know when it’s done.

Thanks again for your help.

Best,

Y

Le sam. 9 nov. 2019 à 21:30, Pierre Karashchuk <notifications@github.com> a
écrit :
