### ISSUE TITLE
Could not install wxPython in Linux (google colab)

### ISSUE THREAD

**Issue by Virginia9733** [lambdaloop/anipose#62]
I tried to install anipose in Colab. Cuz my laptop doesn't have a GPU

First I install conda, then I created then conda env.
I could not install wxPython in colab with the error.

%%shell
eval "$(conda shell.bash hook)" # copy conda command to shell
conda activate anipose_env

python -m pip install -U
-f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04
wxPython

I got this error message:
Looking in links: https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04
Collecting wxPython
Using cached wxPython-4.1.1.tar.gz (66.0 MB)
Requirement already satisfied: pillow in /usr/local/envs/anipose_env/lib/python3.7/site-packages (from wxPython) (8.2.0)
Requirement already satisfied: six in /usr/local/envs/anipose_env/lib/python3.7/site-packages (from wxPython) (1.15.0)
Requirement already satisfied: numpy in /usr/local/envs/anipose_env/lib/python3.7/site-packages (from wxPython) (1.17.5)
Building wheels for collected packages: wxPython
Building wheel for wxPython (setup.py) ... error
ERROR: Failed building wheel for wxPython
Running setup.py clean for wxPython
Failed to build wxPython
Installing collected packages: wxPython
Running setup.py install for wxPython ... error
ERROR: Command errored out with exit status 1: /usr/local/envs/anipose_env/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bve7chve/wxpython_0bded69748294a3ab1cc8b713561d14a/setup.py'"'"'; file='"'"'/tmp/pip-install-bve7chve/wxpython_0bded69748294a3ab1cc8b713561d14a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(file) if os.path.exists(file) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record /tmp/pip-record-x4tzej7u/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/envs/anipose_env/include/python3.7m/wxPython Check the logs for full command output.
CalledProcessError Traceback (most recent call last)
in ()
1
----> 2 get_ipython().run_cell_magic('shell', '', 'eval "$(conda shell.bash hook)" # copy conda command to shell\nconda activate anipose_env\n\npython -m pip install -U \\n -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04 \\n wxPython')

2 frames
/usr/local/lib/python3.7/dist-packages/google/colab/_system_commands.py in check_returncode(self)
137 if self.returncode:
138 raise subprocess.CalledProcessError(
--> 139 returncode=self.returncode, cmd=self.args, output=self.output)
140
141 def repr_pretty(self, p, cycle): # pylint:disable=unused-argument

CalledProcessError: Command 'eval "$(conda shell.bash hook)" # copy conda command to shell
conda activate anipose_env

python -m pip install -U
-f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04
wxPython' returned non-zero exit status 1.

I skipped this part and following the installation instruction. Then I could import anipose in the conda env.
However, when I run anipose analyze, I got the error message:
![Screen Shot 2021-06-03 at 7 14 23 PM](https://user-images.githubusercontent.com/61534754/120641764-98141400-c4a6-11eb-95ae-d1f2b9ad9f8c.png)

The colab notebook is here:

https://colab.research.google.com/drive/1KG48rQAs4VnvRcc6Ux3qT0vYieiCZnSC?usp=sharing

Many thanks!

**Comment by roaldarbol** [comment]
It seems that the exact error arises within DeepLabCut, and not anipose - the path lists `python3.7/site-packages/deeplabcut`. And it seems you're running Linux, which combines poorly with wx; see e.g. [this recent issue](https://github.com/DeepLabCut/DeepLabCut/issues/1233) for DLC. It suggests that wx should not be installed with `pip` but rather using Anaconda: `conda install -c anaconda wxpython` - maybe that'll solve your problem too?
I think I'd try avoiding the conda-within-colab approcah and keep to the simpler alternative I mentioned in #53, but if you decide to power through let us know how it goes! 👍

**Comment by Virginia9733** [comment]
Thank you so much for your kind suggestion! 
I just noticed in this Q&A, it might not be possible to install wxPython in colab.
https://stackoverflow.com/questions/59443140/wxpython-installation-failed-on-google-colab

But will try to find a solution. Thank you!

**Comment by Virginia9733** [comment]
I followed the suggestion of roaldarbol to install wxpython in colab by using conda install -c anaconda expython. It successed. However, when I run anipose analyze, I got new error message :-(

ImportError: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

![Screen Shot 2021-06-03 at 10 22 05 PM](https://user-images.githubusercontent.com/61534754/120661070-86d50280-c4ba-11eb-8941-d908e026515c.png)

the colab notebook could be find here:
https://colab.research.google.com/drive/1CSLvxBA1kwNkl4GSf43rNsaJ40ImlyfY?usp=sharing

**Comment by lambdaloop** [comment]
@Virginia9733 
Anipose doesn't use the wx library directly, it comes from DeepLabCut.
It's used in the GUI in DeepLabCut. 

You can see how to run DeepLabCut without using the GUI here (and thus make it work in colab):
https://github.com/DeepLabCut/DeepLabCut/issues/653
