### ISSUE TITLE
Can I get Demo Files for "Flies"? 

### ISSUE THREAD

**Issue by rim-yu** [lambdaloop/anipose#66]
Hi! I am Rim Yu. :))

Can I get Demo Files for "Flies" not "Hand-Demo"? 

Thank you for your support!

**Comment by katierupp** [comment]
Hi @rim-yu, we do not have any demo files available for flies at the moment. However, the Anipose paper will be released before the end of the month, and we will have a fly dataset to share with that soon. Thank you for your patience!
