### ISSUE TITLE
Why can't I run anipose tutorial successfully

### ISSUE THREAD

**Issue by yingxuanshi** [lambdaloop/anipose#73]
I downloaded anipose tutorial, but I met some troubles. I can not generate 3d video successfully.

My computer: Win10   anaconda3    RTX3080   cuda_10.0.130_411.31_win10    

$conda create -n anipose python=3.8
$conda activate anipose
$conda install tensorflow-gpu=2.5
$pip install deeplabcut[gui]==2.2rc3
$python -m pip install -U wxpython
$python -m pip uninstall opencv-python
$python -m pip install anipose==1.0.1
$conda install ffmpeg
$conda install mayavi
$pip install --upgrade apptools

after I input: $anipose triangulate
Here is the bug:
![image](https://user-images.githubusercontent.com/54396039/137591589-4a8d07c5-234f-4468-9bca-bd2171eeefcb.png)

How can I solve the problem?
Is the version of mayavi not suit with ppython3.8?

**Comment by yingxuanshi** [comment]
I have solved this problem.

**Comment by Mojackhak** [comment]
how I have encountered the same issue. May I kindly ask how you resolved it?
