### ISSUE TITLE
Help request with anipose  "module 'cv2' has no attribute 'CALIB_CB_NORMALIZE_IMAGE'"

### ISSUE THREAD

**Issue by Alberto100591** [lambdaloop/anipose#82]
![image](https://user-images.githubusercontent.com/68699532/160671507-b348972d-eafa-4287-b316-7a272c9e0780.png)![image](https://user-images.githubusercontent.com/68699532/160670776-466d4c68-c0ae-450d-9f0c-30e345a398e5.png)

Good afternoon, my name is Alberto, at this moment I get this error. Could someone help me?
![Captura de Pantalla 2022-03-29 a la(s) 13 17 01](https://user-images.githubusercontent.com/68699532/160692539-e233e440-b9c0-4ba0-8df0-bfb187909d2d.jpg)

**Comment by Guillermo-Hidalgo-Gadea** [comment]
Hi @Alberto100591,
did you manage to solve this problem?
