### ISSUE TITLE
anipose analyze gives no output

### ISSUE THREAD

**Issue by mendlen** [lambdaloop/anipose#86]
Problem: no output generated (including no error) when running anipose analyze on my personal data.

**Output:**
```
(ani) C:\Users\madComp\Desktop\3D_testing>anipose analyze
Analyzing videos...

(ani) C:\Users\madComp\Desktop\3D_testing>
```

The config YAML and TOML files have the appropriate DLC model addresses; I'm able to use anipose analyze for the tutorial within this same without problem, so I'm assuming it has something to do with my config TOML for this project.

**Config**
```
project = "3D_testing" 
model_folder = 'C:\Users\madComp\Desktop\3D_testing\COTask-Linea-2021-10-18'  # path to the DeepLabCut project folder

nesting = 0

[pipeline]
videos_raw = "videos-raw"

[labeling]
scheme = [
    ['D2TIP']
]


[calibration]
# checkerboard / charuco / aruco
board_type = "checkerboard"

# number of inner corners per side for checkerboard
board_size = [9, 6] 

# If charuco or checkerboard, square side length
board_square_side_length = 25.4 # mm

animal_calibration = false
fisheye = false

calibration_init = 'calibration_init.toml'

[manual_verification]
manually_verify = true

[triangulation]
triangulate = true
cam_regex = '(left|right|top)Cam'
cam_align = 'topCam'


# Settings for a threshold filter
# Removes data outside threshold (probably errors in tracking), and interpolates
[filter]
enabled = true
medfilt = 13 #length of median filter
offset_threshold = 25 # offset from median filter to count as jump
score_threshold = 0.8 # score below which to count as bad
spline = true # interpolate using cubic spline instead of linear
type = "autoencoder"
autoencoder_path = "autoencoder.pickle"
```

**Comment by matiarj** [comment]
I'm also running into this issue

**Comment by Guillermo-Hidalgo-Gadea** [comment]
Hi @mendlen and @matiarj , 

this seems to happen when the `Analyzing videos...` loop starts, but can't find any videos or DLC model to actually start analyzing. 
When anipose reeally starts analyzing videos, you will get an output listing the video it is analyzing, together with a progressbar like this: 
`  2%|▊                                                    | 1848/92480 [01:50<1:21:03, 18.64it/s]`

You may want to try specifying the `video_extension = "mp4"` and making sure `nesting = 0` is correct, this has confused me a few time, too.

hope this helps, 
Guillermo

**Comment by mendlen** [comment]
That worked, thank you!
