### ISSUE TITLE
Anipose won't analyze

### ISSUE THREAD

**Issue by kewe7879** [lambdaloop/anipose#96]
When I run "anipose analyze" on the anaconda prompt, the names of the videos run across the screen, but there's no analysis. Does anyone have any idea of where I could start looking to solve this problem? I've checked the names of the calibration and the videos, and they match. And Anipose does seem to be able to find the videos, it just doesn't do anything with them.

**Comment by Darth-Gabagool** [comment]
I would start by 

1. Making sure your folder structure mirrors the one specified in the documentation. It's very easy to make a simple mistake like naming "videos-raw" as something like "Videos-raw" which will throw problems if it's not specified in the config.toml

2. Speaking of .toml files, going through your config.toml with a fine tooth comb is helpful most of the time. Anipose is very picky about convention and little things will completely boggle the program.

If you haven't already I strongly suggest you download and use the tutorial files as a reference for writing configuration files and folder structure.

**Comment by kewe7879** [comment]
I've downloaded the tutorial files as a reference and put them through our system to make sure we have everything downloaded correctly. I've made sure to rename things as closely as possible to the folder that we downloaded (so videos-raw is just that, but the name of the lab is different; so is the date). I've had 2 people besides myself look through the files as well. I've gone through the .toml file a few times, and cannot find anything in there that I didn't see in the documentation. Neither could the others in the lab, but maybe someone else could?
![Screenshot 2022-08-15 115413](https://user-images.githubusercontent.com/108294785/184689573-4dc224fb-d240-4117-ad26-0e55b90ed18a.png)
![Screenshot 2022-08-15 115520](https://user-images.githubusercontent.com/108294785/184689575-dcf6bb9b-4613-43ed-9035-33765b9c8b8d.png)
![Screenshot 2022-08-15 115547](https://user-images.githubusercontent.com/108294785/184689577-607a2d56-9956-4f41-89a3-1542bfd61450.png)
![Screenshot 2022-08-15 115607](https://user-images.githubusercontent.com/108294785/184689578-7a925d29-b636-4810-a730-2090abbdea1b.png)
![Screenshot 2022-08-15 115621](https://user-images.githubusercontent.com/108294785/184689579-ae98bcdc-930d-4ab1-97c5-fba649456f13.png)
![Screenshot 2022-08-15 115643](https://user-images.githubusercontent.com/108294785/184689581-7525a3c7-a3e1-458c-9e78-be4fe9917911.png)
![Screenshot 2022-08-15 115717](https://user-images.githubusercontent.com/108294785/184689582-d0de15ba-1263-4e73-916e-2645b36d97f9.png)
![Screenshot 2022-08-15 115737](https://user-images.githubusercontent.com/108294785/184689584-6e956ebf-a320-422f-beb4-3e6f7143b3ae.png)

**Comment by kewe7879** [comment]
I've figured out the analysis issue! avi needs to be lower case
