### ISSUE TITLE
Struggling to get a calibration .toml 

### ISSUE THREAD

**Issue by kewe7879** [lambdaloop/anipose#98]
There was a similar issue to this before, and the naming convention for the cameras ended up being the issue. I have tried renmaing my cam_regex a few times, and nothing seems to be working. Someone in the past issue said that they would update Anipose so that if it was a naming issue, Anipose would say it was (I'm not getting this error). I keep getting: IndexError: list index out of range. Is this really just a naming issue, or is there something else I should look for to fix this issue?
![Screenshot 2022-08-18 151653](https://user-images.githubusercontent.com/108294785/185496927-0c4bec5d-6deb-48b9-a1a5-550099b9a13e.png)
![Screenshot 2022-08-18 151741](https://user-images.githubusercontent.com/108294785/185496928-2dc28181-3ebc-41f1-a933-fadca53d9310.png)

**Comment by AthiemoneZero** [comment]
The same problem here. But in a API windows using [aniposelib](https://anipose.readthedocs.io/en/latest/aniposelib-tutorial.html), this problem can be solved. Still have no idea how this could happen :(

**Comment by lambdaloop** [comment]
@kewe7879  You get this error when there are no commonly detected boards between two cameras. 

@AthiemoneZero 
It should be the same error in `aniposelib` for the same videos though, I'm not sure how it could work there but not in anipose? Strange

In the future, https://github.com/mprib/pyxy3d looks promising for supporting interactive calibration for anipose projects, to help troubleshoot this kind of error.

**Comment by AthiemoneZero** [comment]
> @kewe7879 You get this error when there are no commonly detected boards between two cameras.
> 
> @AthiemoneZero It should be the same error in `aniposelib` for the same videos though, I'm not sure how it could work there but not in anipose? Strange
> 
> In the future, a tool like https://github.com/mprib/pyxy3d looks promising for supporting interactive calibration for anipose projects, to help troubleshoot this kind of error.

This looks great! But seems no support for off-line reconstruction other than webcam so far.

As for the conflict between `anipose`  and `aniposelib`, I didnt notice any possible clues for solving it. I will keep testing and show out helpful messages as best as I can.
